#!/usr/bin/env python3
"""Module that defines an async comprehension using async_generator."""

from typing import List
import asyncio

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Collect 10 random numbers using an async comprehension
    over async_generator.

    This coroutine uses an async comprehension to collect 10 random numbers
    generated by async_generator. It then returns these numbers as a list.

    Returns:
        List[float]: A list of 10 random float numbers between 0 and 10.
    """
    return [number async for number in async_generator()]
